#!/usr/bin/env bash
#This script uses while, if, elif, and else to display Holberton School 10 times
i=0
while ((i < 10))
do
    if (( i == 4))
    then
    	echo "bad luck"
    elif (( i == 8))
    then
    	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
