#!/usr/bin/env bash
#This script will use while and case to display numbers 1 to 20 plus statements
n=1
while ((n <= 20))
do
    echo "$n"
    case $n in
    	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((n++))
done
