#!/usr/bin/env bash
#Script to display time in hours and minutes using while loop
h=0
m=0
while ((h <= 12))
do
    echo "Hour:$h"
    ((h++))
    while ((m< 60))
    do
	echo $m
	((m++))
    done
done
