#!/usr/bin/env bash
#Script to display time in hours and minutes using while loop
h=0
while ((h <= 12));
do
    echo "Hour: $h"
    ((h++))
    m=1
    while ((m <= 59))
    do
	echo $m
	((m++))
    done
done
